listen:
    address: 172.17.0.1
    port: 8080
send:
    address: 134.100.28.31
    port: 9999
mappings: mappings/dionaea/
broker:
    topic: honeypot/dionaea/
    endpoint_prefix: beemaster-connector-rpi-
