version: '2'
services:
  connector:
    build: ./connector
    command: ["config-uhh.yaml"]
  dionaea:
    build: ./dionaea
    volumes:
      - /var/beemaster/log/dionaea-logs:/var/dionaea/logs
      - /var/beemaster/dionaea/binaries:/var/dionaea/binaries/
      - /var/beemaster/dionaea/ftp:/var/dionaea/roots/ftp
    ports:
      - "21:21"
      - "80:80"
      - "443:443"
      - "445:445"
      - "3306:3306"