version: '2'
services:
  connector:
    build: ./connector
    command: ["config-uhh.yaml"]
  dionaea:
    build: ./dionaea
    depends_on:
      - connector
    ports:
      - "21:21"
      - "23:23"
      - "53:53/udp"
      - "53:53"
      - "80:80"
      - "123:123/udp"
      - "443:443"
      - "445:445"
      - "3306:3306"
