listen:
    address: 0.0.0.0
    port: 8080
send:
    address: bro
    port: 9999
mappings: mappings/dionaea/
broker:
    topic: honeypot/dionaea/
    endpoint: dioEp
#connectorId: It is important to set your unique ID here