.PHONY: test test_sender test_mapper test_conn-config


test:
	make test_mapper test_sender test_conn-config

test_mapper:
	python test_mapper.py

test_sender:
	python test_sender.py

test_conn-config:
	python test_conn-config.py
